spring:
   datasource:
      plataform: ORACLE
      driver-class-name: oracle.jdbc.driver.OracleDriver #org.h2.Driver
      url: jdbc:oracle:thin:@localhost:1522:apdb
      username: ap_admin
      password: 123
      initialize: true
      hikari:
         connection-timeout: 30000
         maximum-pool-size: 50
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      #database-platform: org.hibernate.dialect.Oracle10gDialect